[env:esp32s3_n16r2]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 921600

; ESP32-S3-WROOM N16R2: 16 MB Flash + 2 MB PSRAM
board_build.arduino.memory_type = qio_qspi
board_build.flash_mode = qio
board_build.psram_type = qio
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = default_16MB.csv

build_flags =
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
  Vrekrer/Vrekrer SCPI parser@^0.5.0
  arduino-libraries/Ethernet@^2.0.2
  adafruit/Adafruit MCP23017 Arduino Library@^2.3.2
  adafruit/Adafruit SSD1306@^2.5.13
  adafruit/Adafruit GFX Library@^1.12.1
